name: Qodana - Code Inspection Example

on:
  workflow_dispatch:
  push:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Qodana dependencies
        uses: actions/cache@v2
        with:
          path: ~/work/_temp/_github_home/qodana-cache
          key: ${{ runner.os }}-qodana-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-qodana-${{ github.ref }}
            ${{ runner.os }}-qodana-

      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v2.2-eap
        with:
          fail-threshold: 1
          baseline: ".github/workflows/baseline.sarif.json"
          baseline-include-absent: true

      - name: Save Qodana's results to artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/qodana
