name: Qodana - Code Inspection

on:
  workflow_dispatch:

jobs:
  code_inspection:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Qodana dependencies
        uses: actions/cache@v2
        with:
          path: ~/work/_temp/_github_home/cache
          key: ${{ runner.os }}-qodana-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-qodana-${{ github.ref }}
            ${{ runner.os }}-qodana-

      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v2.0-eap

      - name: Archive results
        uses: actions/upload-artifact@v2
        with:
          name: qodana-results
          if-no-files-found: error
          path: report/results

      - name: Print error message
        if: failure()
        run: |
          echo "Qodana - has failed. Please contact our support team by email at qodana-support@jetbrains.com. Attach qodana-error-logs.zip to your message."